name: Build & Test CI

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      head_tag: ${{ steps.head_tag.outputs.head_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Retrieve tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Check if Git tag exists
        id: head_tag
        run: echo "::set-output name=head_tag::$(git tag --points-at HEAD)"
        if: startsWith(github.ref, 'refs/heads/')

  build:
    name: Build and test
    runs-on: ubuntu-latest
    needs: prepare
    if: "!contains(github.event.head_commit.message, '[ci skip]') && (!startsWith(github.ref, 'refs/heads/') || !needs.prepare.outputs.head_tag)"
    strategy:
      matrix:
        node_version: ['12', '14']

    steps:
      - name: Check out the code
        uses: actions/checkout@v2.4.0

      - name: Set up Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Cache Node modules
        uses: actions/cache@v2.1.7
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node_version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node_version }}-
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Clean install and test
        run: npm cit

  release:
    name: Prepare the release
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Get release description
        id: release_params
        run: |
          SUBJECT="$(git for-each-ref "${{ github.ref }}" --format="%(contents:subject)")"
          BODY="$(git for-each-ref "${{ github.ref }}" --format="%(contents:body)")"
          echo "::set-output name=subject::${SUBJECT}"
          echo "::set-output name=body::${BODY}"

      - name: Create a release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ steps.release_params.subject }}
          body: ${{ steps.release_params.body }}
