name: Package Audit

on:
  push:
    branches:
      - '**'
    paths:
      - package.json
      - package-lock.json
      - .github/workflows/package-audit.yml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  audit-npm:
    name: NPM Audit
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          disable-sudo: true
          allowed-endpoints:
            api.github.com:443
            github.com:443
            objects.githubusercontent.com:443
            nodejs.org:443
            registry.npmjs.org:443

      - name: Audit with NPM
        uses: myrotvorets/composite-actions/node-package-audit@d48d1c16e5782ea32f56fe24da600ca2028ed8b1 # master
